apiVersion: v1
kind: Secret
metadata:
  name: tekton-pipelines-webhook-overlay
  namespace: tap-install
stringData:
  tekton-pipelines-webhook-overlay.yml: |
    #@ load("@ytt:overlay", "overlay")
    
    #@overlay/match by=overlay.subset({"kind": "HorizontalPodAutoscaler", "metadata": {"name": "tekton-pipelines-webhook"}}), expects="0+"
    ---
    spec:
      #@overlay/match missing_ok=True
      minReplicas: 10
      maxReplicas: 10
      #@overlay/remove
      metrics:
    
    #@overlay/match by=overlay.subset({"kind": "HorizontalPodAutoscaler", "metadata": {"name": "tekton-pipelines-webhook"}}), expects="0+"
    ---
    spec:
      #@overlay/match missing_ok=True
      metrics:
        - resource:
            name: cpu
            target:
              averageUtilization: 75
              type: Utilization
          type: Resource
    
    #@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"tekton-pipelines-webhook"}}), expects="1+"
    ---
    spec:
      #@overlay/replace via=lambda left, _: left
      selector:
    ---
    apiVersion: kapp.k14s.io/v1alpha1
    kind: Config
    rebaseRules:
      - path:
          - spec
          - replicas
        type: copy
        sources:
          - existing
          - new
        resourceMatchers:
          - apiGroupKindMatcher:
              apiGroup: apps
              kind: Deployment
      - paths:
          - [data, ca-cert.pem]
          - [data, server-cert.pem]
          - [data, server-key.pem]
        type: copy
        sources: [new,existing]
        resourceMatchers:
          - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
